### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by garosan** [gitnix/chrome-extension-udemy-playback-rate#14]
As of yesterday I noticed extension is not working anymore. 
I have it installed on 2 different Windows 10 computers and now when I load Udemy the extra controls are not there anymore.
Thanks for your awesome extension anyways!

**Comment by augustmuir** [comment]
Not to take away from gitnix work but I made my own version while this was down:
https://github.com/augustkimo/Udemy-Custom-Speed-Changer/
https://chrome.google.com/webstore/detail/udemy-custom-speed-change/mfinfiagnpnbijihonbeadgnfbihhpcf/

**Comment by garosan** [comment]
That's awesome @augustkimo you saved my day :)
